const { contextBridge, ipcRenderer } = require('electron') as typeof import('electron')

function subscribe(channel: string, callback: (payload: unknown) => void) {
  const listener = (_event: Electron.IpcRendererEvent, payload: unknown) => callback(payload)
  ipcRenderer.on(channel, listener)
  return () => ipcRenderer.removeListener(channel, listener)
}

contextBridge.exposeInMainWorld('prism', {
  listProviders: () => ipcRenderer.invoke('providers:list'),
  loadSessions: () => ipcRenderer.invoke('sessions:load'),
  saveSessions: (sessions: unknown) => ipcRenderer.invoke('sessions:save', sessions),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  updateSettings: (settings: unknown) => ipcRenderer.invoke('settings:update', settings),
  chooseWorkspace: () => ipcRenderer.invoke('workspace:choose'),
  listLibrary: () => ipcRenderer.invoke('library:list'),
  searchArxiv: (input: string) => ipcRenderer.invoke('arxiv:search', input),
  autocompletePapers: (input: string) => ipcRenderer.invoke('paper:autocomplete', input),
  openArxiv: (arxivId: string) => ipcRenderer.invoke('arxiv:open', arxivId),
  downloadPaper: (paper: unknown) => ipcRenderer.invoke('paper:download', paper),
  readPaperPdf: (arxivId: string) => ipcRenderer.invoke('paper:pdf', arxivId),
  readLatexStructure: (arxivId: string) => ipcRenderer.invoke('paper:latex-structure', arxivId),
  readPaperFigures: (arxivId: string) => ipcRenderer.invoke('paper:figures', arxivId),
  openNotes: () => ipcRenderer.invoke('notes:open'),
  readPaperNote: (arxivId: string) => ipcRenderer.invoke('paper:note:read', arxivId),
  savePaperNote: (arxivId: string, request: unknown) => ipcRenderer.invoke('paper:note:save', arxivId, request),
  listTemplates: () => ipcRenderer.invoke('templates:list'),
  saveTemplate: (request: unknown) => ipcRenderer.invoke('templates:save', request),
  deleteTemplate: (id: string) => ipcRenderer.invoke('templates:delete', id),
  setDefaultTemplate: (nodeType: string, id: string) => ipcRenderer.invoke('templates:set-default', nodeType, id),
  listKnowledgeNodes: () => ipcRenderer.invoke('knowledge:list'),
  searchKnowledge: (query: string) => ipcRenderer.invoke('knowledge:search', query),
  listKnowledgeDataViews: () => ipcRenderer.invoke('knowledge:views'),
  createKnowledgeNode: (request: unknown) => ipcRenderer.invoke('knowledge:create', request),
  readKnowledgeNode: (id: string) => ipcRenderer.invoke('knowledge:read', id),
  saveKnowledgeNode: (id: string, request: unknown) => ipcRenderer.invoke('knowledge:save', id, request),
  updateKnowledgeProperties: (id: string, patch: unknown, expectedRevision: string) => ipcRenderer.invoke('knowledge:update-properties', id, patch, expectedRevision),
  deleteKnowledgeNode: (id: string) => ipcRenderer.invoke('knowledge:delete', id),
  listKnowledgeBacklinks: (id: string) => ipcRenderer.invoke('knowledge:backlinks', id),
  listKnowledgeRelations: (id: string) => ipcRenderer.invoke('knowledge:relations:list', id),
  createKnowledgeRelation: (request: unknown) => ipcRenderer.invoke('knowledge:relations:create', request),
  deleteKnowledgeRelation: (request: unknown) => ipcRenderer.invoke('knowledge:relations:delete', request),
  listEvidenceAnchors: () => ipcRenderer.invoke('evidence:list'),
  openEvidenceAnchor: (anchor: unknown) => ipcRenderer.invoke('evidence:open', anchor),
  onOpenEvidenceAnchor: (callback: (anchor: unknown) => void) => subscribe('evidence:open-requested', callback),
  listEvidenceBacklinks: (anchor: unknown) => ipcRenderer.invoke('evidence:backlinks', anchor),
  openKnowledgeNodeInNotes: (id: string) => ipcRenderer.invoke('knowledge:open-in-notes', id),
  onOpenKnowledgeNode: (callback: (id: unknown) => void) => subscribe('knowledge:open-requested', callback),
  savePaperFigure: (arxivId: string, figureId: string, dataUrl: string, metadata: unknown) => ipcRenderer.invoke('paper:figure:save', arxivId, figureId, dataUrl, metadata),
  readTranslation: (arxivId: string) => ipcRenderer.invoke('translation:read', arxivId),
  savePaperAnchors: (arxivId: string, anchors: unknown) => ipcRenderer.invoke('paper:anchors:save', arxivId, anchors),
  startTranslation: (arxivId: string, segments: unknown, options?: unknown) => ipcRenderer.invoke('translation:start', arxivId, segments, options),
  cancelTranslation: (arxivId: string) => ipcRenderer.invoke('translation:cancel', arxivId),
  sendMessage: (request: unknown) => ipcRenderer.invoke('chat:send', request),
  cancelMessage: (sessionId: string) => ipcRenderer.invoke('chat:cancel', sessionId),
  onChatEvent: (callback: (event: unknown) => void) => subscribe('chat:event', callback),
  onChatDone: (callback: (event: unknown) => void) => subscribe('chat:done', callback),
  onChatError: (callback: (event: unknown) => void) => subscribe('chat:error', callback),
  onTranslationProgress: (callback: (event: unknown) => void) => subscribe('translation:progress', callback),
  onTranslationDone: (callback: (event: unknown) => void) => subscribe('translation:done', callback),
  onTranslationError: (callback: (event: unknown) => void) => subscribe('translation:error', callback),
})
