const { contextBridge, ipcRenderer } = require('electron') as typeof import('electron')

function subscribe(channel: string, callback: (payload: unknown) => void) {
  const listener = (_event: Electron.IpcRendererEvent, payload: unknown) => callback(payload)
  ipcRenderer.on(channel, listener)
  return () => ipcRenderer.removeListener(channel, listener)
}

contextBridge.exposeInMainWorld('prism', {
  setAppearance: (theme: unknown) => ipcRenderer.invoke('appearance:set', theme),
  listProviders: () => ipcRenderer.invoke('providers:list'),
  loginProvider: (provider: unknown) => ipcRenderer.invoke('provider:login', provider),
  logoutProvider: (provider: unknown) => ipcRenderer.invoke('provider:logout', provider),
  onProviderAuthData: (callback: (event: unknown) => void) => subscribe('provider:auth:data', callback),
  loadSessions: () => ipcRenderer.invoke('sessions:load'),
  saveSessions: (sessions: unknown) => ipcRenderer.invoke('sessions:save', sessions),
  onSettingsChanged: (callback: (settings: unknown) => void) => subscribe('settings:changed', callback),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  updateSettings: (settings: unknown) => ipcRenderer.invoke('settings:update', settings),
  reconnectPaperStorage: () => ipcRenderer.invoke('storage:reconnect-papers'),
  onLibraryChanged: (callback: (records: unknown) => void) => subscribe('library:changed', callback),
  choosePaperStorage: (reset = false) => ipcRenderer.invoke('storage:choose-papers', reset),
  chooseWorkspace: () => ipcRenderer.invoke('workspace:choose'),
  listLibrary: () => ipcRenderer.invoke('library:list'),
  searchCrossref: (query: string) => ipcRenderer.invoke('papers:search-crossref', query),
  openDoi: (id: string) => ipcRenderer.invoke('papers:open-doi', id),
  searchArxiv: (input: string) => ipcRenderer.invoke('arxiv:search', input),
  autocompletePapers: (input: string) => ipcRenderer.invoke('paper:autocomplete', input),
  openArxiv: (arxivId: string) => ipcRenderer.invoke('arxiv:open', arxivId),
  importLocalPaper: (metadata?: unknown) => ipcRenderer.invoke('paper:import-local', metadata),
  downloadPaper: (paper: unknown) => ipcRenderer.invoke('paper:download', paper),
  readPaperPdf: (arxivId: string) => ipcRenderer.invoke('paper:pdf', arxivId),
  readLatexStructure: (arxivId: string) => ipcRenderer.invoke('paper:latex-structure', arxivId),
  readPaperFigures: (arxivId: string) => ipcRenderer.invoke('paper:figures', arxivId),
  openNotes: () => ipcRenderer.invoke('notes:open'),
  openPaperInReader: (arxivId?: string) => ipcRenderer.invoke('reader:open', arxivId),
  onOpenPaperInReader: (callback: (arxivId: unknown) => void) => subscribe('reader:open-paper', callback),
  capturePaperNote: (request: unknown) => ipcRenderer.invoke('paper:note:capture', request),
  listTemplates: () => ipcRenderer.invoke('templates:list'),
  saveTemplate: (request: unknown) => ipcRenderer.invoke('templates:save', request),
  deleteTemplate: (id: string) => ipcRenderer.invoke('templates:delete', id),
  setDefaultTemplate: (nodeType: string, id: string) => ipcRenderer.invoke('templates:set-default', nodeType, id),
  setFavoriteTemplate: (id: string, favorite: boolean) => ipcRenderer.invoke('templates:set-favorite', id, favorite),
  listKnowledgeNodes: () => ipcRenderer.invoke('knowledge:list'),
  searchResearchKnowledge: (query: string) => ipcRenderer.invoke('research:search', query),
  suggestKnowledge: (nodeId: string) => ipcRenderer.invoke('research:suggest', nodeId),
  listCurationQueue: () => ipcRenderer.invoke('knowledge:curation:list'),
  syncNoteLinks: (id: string) => ipcRenderer.invoke('knowledge:links:sync', id),
  pruneEmptySections: (id: string) => ipcRenderer.invoke('knowledge:prune-empty-sections', id),
  listAutoUnread: () => ipcRenderer.invoke('knowledge:auto-unread:list'),
  clearAutoUnread: (id: string) => ipcRenderer.invoke('knowledge:auto-unread:clear', id),
  refreshPaperDigest: (paperNodeId: string, options?: unknown) => ipcRenderer.invoke('paper:digest:refresh', paperNodeId, options),
  refreshVaultDigests: () => ipcRenderer.invoke('knowledge:digest:refresh-vault'),
  onVaultChanged: (callback: (event: unknown) => void) => subscribe('knowledge:vault-changed', callback),
  restoreKnowledgeNode: (trashedRelativePath: string) => ipcRenderer.invoke('knowledge:restore', trashedRelativePath),
  listPaperCitations: (arxivId: string, options?: unknown) => ipcRenderer.invoke('paper:citations', arxivId, options),
  readPaperStructure: (arxivId: string) => ipcRenderer.invoke('paper:structure', arxivId),
  refinePaperStructure: (arxivId: string) => ipcRenderer.invoke('paper:structure:refresh', arxivId),
  runModelSuggestions: (paperNodeId: string) => ipcRenderer.invoke('research:suggest:model', paperNodeId),
  reviewModelSuggestion: (request: unknown) => ipcRenderer.invoke('research:suggest:model:review', request),
  promoteMemo: (request: unknown) => ipcRenderer.invoke('knowledge:curation:promote-memo', request),
  promoteApplyNote: (request: unknown) => ipcRenderer.invoke('knowledge:curation:promote-apply', request),
  mergeConcepts: (request: unknown) => ipcRenderer.invoke('knowledge:curation:merge-concepts', request),
  openKnowledgeNodeInObsidian: (request: unknown) => ipcRenderer.invoke('knowledge:open-in-obsidian', request),
  createKnowledgeNode: (request: unknown) => ipcRenderer.invoke('knowledge:create', request),
  applyTemplateSections: (request: unknown) => ipcRenderer.invoke('knowledge:apply-template-sections', request),
  readKnowledgeNode: (id: string, vaultId?: string) => ipcRenderer.invoke('knowledge:read', id, vaultId),
  listPendingNoteRecoveries: () => ipcRenderer.invoke('knowledge:recoveries'),
  readPendingNoteRecovery: (id: string, kind: string) => ipcRenderer.invoke('knowledge:recovery-read', id, kind),
  recoverPendingNote: (id: string, kind: string) => ipcRenderer.invoke('knowledge:recovery-restore', id, kind),
  listNoteHistory: (id: string, vaultId?: string) => ipcRenderer.invoke('knowledge:history', id, vaultId),
  readNoteHistory: (id: string, entryId: string, vaultId?: string) => ipcRenderer.invoke('knowledge:history-read', id, entryId, vaultId),
  saveKnowledgeNode: (id: string, request: unknown) => ipcRenderer.invoke('knowledge:save', id, request),
  updateKnowledgeProperties: (id: string, patch: unknown, expectedRevision: string) => ipcRenderer.invoke('knowledge:update-properties', id, patch, expectedRevision),
  deleteKnowledgeNode: (id: string) => ipcRenderer.invoke('knowledge:delete', id),
  listKnowledgeBacklinks: (id: string) => ipcRenderer.invoke('knowledge:backlinks', id),
  copyKnowledgeEvidence: (request: unknown) => ipcRenderer.invoke('knowledge:evidence:copy', request),
  listKnowledgeGraph: () => ipcRenderer.invoke('knowledge:graph'),
  listKnowledgeGraphInsights: () => ipcRenderer.invoke('knowledge:graph:insights'),
  listKnowledgeRelations: (id: string) => ipcRenderer.invoke('knowledge:relations:list', id),
  createKnowledgeRelation: (request: unknown) => ipcRenderer.invoke('knowledge:relations:create', request),
  deleteKnowledgeRelation: (request: unknown) => ipcRenderer.invoke('knowledge:relations:delete', request),
  reviewKnowledgeRelation: (request: unknown) => ipcRenderer.invoke('knowledge:relations:review', request),
  listEvidenceAnchors: () => ipcRenderer.invoke('evidence:list'),
  openEvidenceAnchor: (anchor: unknown) => ipcRenderer.invoke('evidence:open', anchor),
  onOpenEvidenceAnchor: (callback: (anchor: unknown) => void) => subscribe('evidence:open-requested', callback),
  listEvidenceBacklinks: (anchor: unknown) => ipcRenderer.invoke('evidence:backlinks', anchor),
  openKnowledgeNodeInNotes: (id: string) => ipcRenderer.invoke('knowledge:open-in-notes', id),
  onOpenKnowledgeNode: (callback: (id: unknown) => void) => subscribe('knowledge:open-requested', callback),
  readSavedFigure: (paperId: string, anchorId: string) => ipcRenderer.invoke('paper:figure:read', paperId, anchorId),
  savePaperFigure: (arxivId: string, figureId: string, dataUrl: string, metadata: unknown) => ipcRenderer.invoke('paper:figure:save', arxivId, figureId, dataUrl, metadata),
  readTranslation: (arxivId: string) => ipcRenderer.invoke('translation:read', arxivId),
  savePaperAnchors: (arxivId: string, anchors: unknown) => ipcRenderer.invoke('paper:anchors:save', arxivId, anchors),
  startTranslation: (arxivId: string, segments: unknown, options?: unknown) => ipcRenderer.invoke('translation:start', arxivId, segments, options),
  cancelTranslation: (arxivId: string) => ipcRenderer.invoke('translation:cancel', arxivId),
  sendMessage: (request: unknown) => ipcRenderer.invoke('chat:send', request),
  cancelMessage: (sessionId: string) => ipcRenderer.invoke('chat:cancel', sessionId),
  onChatEvent: (callback: (event: unknown) => void) => subscribe('chat:event', callback),
  onChatDone: (callback: (event: unknown) => void) => subscribe('chat:done', callback),
  onChatError: (callback: (event: unknown) => void) => subscribe('chat:error', callback),
  onProviderRateLimits: (callback: (event: unknown) => void) => subscribe('provider:ratelimits', callback),
  onTranslationProgress: (callback: (event: unknown) => void) => subscribe('translation:progress', callback),
  onTranslationDone: (callback: (event: unknown) => void) => subscribe('translation:done', callback),
  onTranslationError: (callback: (event: unknown) => void) => subscribe('translation:error', callback),
})
